export const actionRedux = {
  FETCH_DATA_BREADCRUMB: "FETCH_DATA_BREADCRUMB",
  FETCH_DATA_USER: "FETCH_DATA_USER",
  ADD_LANGUAGE: "ADD_LANGUAGE",
  // CCT Programs
  ADD_MEMBER_LIST_CCT_CONFIRM: "ADD_MEMBER_LIST_CCT_CONFIRM",
  DELETE_MEMBER_LIST_CCT_CONFIRM: "DELETE_MEMBER_LIST_CCT_CONFIRM",
  SET_LIST_MEMBER: "SET_LIST_MEMBER",
};
