export const actionRedux = {
  FETCH_DATA_BREADCRUMB: "FETCH_DATA_BREADCRUMB",
  FETCH_DATA_USER: "FETCH_DATA_USER",
  ADD_LANGUAGE: "ADD_LANGUAGE",
  // CCT Programs
  ADD_MEMBER_LIST_CCT_CONFIRM: "ADD_MEMBER_LIST_CCT_CONFIRM",
  DELETE_MEMBER_LIST_CCT_CONFIRM: "DELETE_MEMBER_LIST_CCT_CONFIRM",
  SET_LIST_MEMBER: "SET_LIST_MEMBER",
  // CM Request Reducer
  ADD_CM_REQUEST_ITEM: "ADD_CM_REQUEST_ITEM",
  DELETE_CM_REQUEST_ITEM: "DELETE_CM_REQUEST_ITEM",
  SET_LIST_CM_REQUEST: "SET_LIST_CM_REQUEST",
  UPDATE_STATUS_PAGE_ON_DEMEND: "UPDATE_STATUS_PAGE_ON_DEMEND",
  // CM Requested Reducer
  ADD_CM_REQUESTED_ITEM: "ADD_CM_REQUESTED_ITEM",
  DELETE_CM_REQUESTED_ITEM: "DELETE_CM_REQUESTED_ITEM",
  SET_LIST_CM_REQUESTED: "SET_LIST_CM_REQUESTED",
  UPDATE_STATUS_PAGE_ON_REQUESTED: "UPDATE_STATUS_PAGE_ON_REQUESTED",
  // CM District Approve Reducer
  ADD_DISTRICT_APPROVE: "ADD_DISTRICT_APPROVE",
  DELETE_DISTRICT_APPROVE: "DELETE_DISTRICT_APPROVE",
  SET_LIST_DISTRICT_APPROVE: "SET_LIST_DISTRICT_APPROVE",
  UPDATE_STATUS_PAGE_ON_DISTRICT_APPROVE: "UPDATE_STATUS_PAGE_ON_DISTRICT_APPROVE",
  // CM Central Approve Reducer
  ADD_CENTRAL_APPROVE: "ADD_CENTRAL_APPROVE",
  DELETE_CENTRAL_APPROVE: "DELETE_CENTRAL_APPROVE",
  SET_LIST_CENTRAL_APPROVE: "SET_LIST_CENTRAL_APPROVE",
  UPDATE_STATUS_PAGE_ON_CENTRAL_APPROVE: "UPDATE_STATUS_PAGE_ON_CENTRAL_APPROVE",
};
