export const PATH = {
  DASHBOARD: "/",
  SYSTEM: "/system",
  DATA_DICTIONARY: "/dataDictionary",
  HOUSEHOLD_MANAGEMENT: "/householdManagement",
  CCT_PROGRAM: "/CCTProgram",
  PAYMENT: "/payment",
  GRIEVANCE_MANAGEMENT: "/grienvanceManagement",
  REPORT_BI: "reportBI",
  SMS_BROADCAST: "SMSBroadcast",
  PROFILE: "/profile",
  PAGE_403: "/error-authentication",
  FUNCTION_LIST_MANAGEMENT: "/system/functionListManagement",
  RIGHTS_MANAGEMENT: "/system/rightsManagement",
  ROLE_MANAGEMENT: "/system/roleManagement",
  USER_MANAGEMENT: "/system/userManagement",
  SYSTEMS_PARAMETERS: "/system/systemsParameters",
  BACKUP_DATABASE: "/system/backupDatabase",
};
