export const PATH = {
  DASHBOARD: "/",
  LOGIN: "/login",
  system: "/system",
  datadictionary: "/datadictionary",
  householdmanagement: "/householdmanagement",
  cctprogram: "/cctprogram",
  paymentmodule: "/paymentmodule",
  grievancemanagement: "/grievancemanagement",
  reportbi: "/reportbi",
  smsbroadcast: "/smsbroadcast",
  PROFILE: "/profile",
  PAGE_403: "/error-authentication",
  FUNCTION_LIST_MANAGEMENT: "/system/functionlistmanagement",
  RIGHTS_MANAGEMENT: "/system/rightsmanagement",
  ROLE_MANAGEMENT: "/system/rolemanagement",
  USER_MANAGEMENT: "/system/usermanagement",
  SYSTEMS_PARAMETERS: "/system/systemparameters",
  BACKUP_DATABASE: "/system/backupdatabase",
  PERMISSIONS_MANAGEMENT: "/system/rolemanagement/permissionmanagement",
  ADD_HOUSEHOLD: "/householdmanagement/householdregistration/addhousehold",
  UPDATE_HOUSEHOLD:
    "/householdmanagement/householdregistration/updatehousehold",
  MEMBER_IN_HOUSEHOLD:
    "/householdmanagement/householdregistration/memberinhousehold",
  UPDATE_MEMBER_IN_HOUSEHOLD:
    "/householdmanagement/householdregistration/updatememberhousehold",
  HOUSEHOLD_REGISTRATION: "/householdmanagement/householdregistration",
  LIST_OF_PROVINCE: "/datadictionary/listofprovince",
  LIST_OF_DISTRICT: "/datadictionary/listofdistrict",
  LIST_OF_VILLAGE: "/datadictionary/listofvillage",
  LIST_OF_WALL_MATERIAL: "/datadictionary/listofwallmaterail",
  LIST_OF_FLOOR_MATERIAL: "/datadictionary/listoffloormaterail",
  LIST_OF_ROOF_MATERIAL: "/datadictionary/listofroofmaterail",
  LIST_OF_DRINKING_WATER: "/datadictionary/listofdrinkingwater",
  LIST_OF_TOILET: "/datadictionary/listoftoilet",
  LIST_OF_ENERGY_SOURCE: "/datadictionary/listofenergysource",
  LIST_OF_ETHNIC: "/datadictionary/listofethnic",
  LIST_OF_LEVEL: "/datadictionary/listoflevel",
  LIST_OF_CLASS: "/datadictionary/listofclass",
  LIST_OF_MAIN_JOB: "/datadictionary/listofmainjob",
  LIST_OF_BUSINESS: "/datadictionary/listofbusiness",
  LIST_OF_PLOT_STATUS: "/datadictionary/listofplotstatus",
  LIST_OF_PLOT_CAUSE: "/datadictionary/listofplotcause",
  LIST_OF_PLOT_TYPE: "/datadictionary/listofplottype",
  LIST_OF_LAND_TYPE: "/datadictionary/listoflandtype",
  LIST_OF_SCHOOL_TYPE: "/datadictionary/listofschooltype",
  LIST_OF_BORROW_REASON: "/datadictionary/listofborrowreason",
  LIST_OF_MAIN_GOOD_AND_SERVICES: "/datadictionary/listofmaingoodandservices",
  DETAIL_HOUSEHOLD:
    "/householdmanagement/householdregistration/detailhousehold",
  ACCOUNT: "/dashboard/account",
  LIST_OF_COOKING_SOURCE: "/datadictionary/listofcookingsource",
  LIST_OF_LANDER_TYPE: "/datadictionary/listoflandertype",
  USERVILLAGE: "/system/uservillage",
  LIST_OF_MARITAL_STATUS: "/datadictionary/listofmaritalstatus",
  LIST_OF_RELATION: "/datadictionary/listofrelation",
  LIST_OF_DISABILITY: "/datadictionary/listofdisability",
  LIST_OF_SCHOOL_ENROLL: "/datadictionary/listofschoolenroll",
  LIST_OF_AREA_MATERAL: "/datadictionary/listofareamateral",
  LIST_OF_SAFETY_AREA: "/datadictionary/listofsafetyarea",
  EROLLMENT: "/cctprogram/enrollment",
  PMTSCORE: "/cctprogram/pmtscore",
  EROLLMENT_AUTO_FROM_PMT_RESULT:"/cctprogram/enrollautofrompmtresult",
  CCT_CONFIRM_STATUS: "/datadictionary/cctconfirmstatus",
};

export const PATH_BREADCRUM = {
  dashboard: "/",
  system: "/system",
  datadictionary: "/datadictionary",
  householdmanagement: "/householdmanagement",
  cctprogram: "/cctprogram",
  PAYpaymentMENT: "/payment",
  GRIEVANCE_MANAGEMENT: "/grienvanceManagement",
  REPORT_BI: "reportBI",
  SMS_BROADCAST: "SMSBroadcast",
  PROFILE: "/profile",
  PAGE_403: "/error-authentication",
  functionlistmanagement: "/system/functionlistmanagement",
  rightsmanagement: "/system/rightsmanagement",
  rolemanagement: "/system/rolemanagement",
  usermanagement: "/system/usermanagement",
  systemparameters: "/system/systemparameters",
  backupdatabase: "/system/backupdatabase",
  permissionmanagement: "/system/roleManagement/permissionmanagement",
  addhousehold: "/householdmanagement/householdregistration/addhousehold",
  updatehousehold: "/householdmanagement/householdregistration/updatehousehold",
  memberinhousehold: "/householdmanagement/householdregistration/memberinhousehold",
  updatememberinhousehold: "/householdmanagement/householdregistration/updatememberhousehold",
  householdregistration: "/householdmanagement/householdregistration",
  listofprovince: "/datadictionary/listofprovince",
  listofdistrict: "/datadictionary/listofdistrict",
  listofvillage: "/datadictionary/listofvillage",
  listofwallmaterail: "/datadictionary/listofwallmaterail",
  listoffloormaterail: "/datadictionary/listoffloormaterail",
  listofroofmaterail: "/datadictionary/listofroofmaterail",
  listofdrinkingwater: "/datadictionary/listofdrinkingwater",
  listoftoilet: "/datadictionary/listoftoilet",
  listofenergysource: "/datadictionary/listofenergysource",
  listofethnic: "/datadictionary/listofethnic",
  listoflevel: "/datadictionary/listoflevel",
  listofclass: "/datadictionary/listofclass",
  listofmainjob: "/datadictionary/listofmainjob",
  listofbusiness: "/datadictionary/listofbusiness",
  listofplotstatus: "/datadictionary/listofplotstatus",
  listofplotcause: "/datadictionary/listofplotcause",
  listofplottype: "/datadictionary/listofplottype",
  listoflandtype: "/datadictionary/listoflandtype",
  listofschooltype: "/datadictionary/listofschooltype",
  listofborrowreason: "/datadictionary/listofborrowreason",
  listofmaingoodandservices: "/datadictionary/listofmaingoodandservices",
  listofmaritalstatus: "/datadictionary/listofmaritalstatus",
  listofrelation: "/datadictionary/listofrelation",
  detailhousehold: "/householdmanagement/householdregistration/detailhousehold",
  account: "/dashboard/account",
  listofcookingsource: "/datadictionary/listofcookingsource",
  listoflandertype: "/datadictionary/listoflandertype",
  uservillage: "/system/uservillage",
  listofdisability: "/datadictionary/listofdisability",
  listofschoolenroll: "/datadictionary/listofschoolenroll",
  listofareamateral: "/datadictionary/listofareamateral",
  listofsafetyarea: "/datadictionary/listofsafetyarea",
  cctconfirmstatus: "/datadictionary/cctconfirmstatus",
  enrollment: "/cctprogram/enrollment",
  pmtscore: "/cctprogram/pmtscore",
  enrollautofrompmtresult:"/cctprogram/enrollautofrompmtresult",
};
